# Generated by Django 5.1.6 on 2025-03-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='filmes',
            field=models.ManyToManyField(blank=True, to='api.filmes'),
        ),
    ]
